version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
  - dependency-name: xregexp
    versions:
    - 4.4.1
    - 5.0.1
